# Paste your list of URLs (exactly as provided) between the triple quotes.
urls = """https://github.com/vmware-archive/ansible-role-greengrass-init
https://github.com/dotnet/immo-redirection-test-renamed
https://github.com/kubernetes-incubator/cri-o
https://github.com/warrant-dev/awesome-dev-conferences
https://github.com/prisma/challenge-sqlite-database
https://github.com/microsoft/typescript
https://github.com/prisma/shopify-app-js
https://github.com/prisma/prisma-json-types-generator
https://github.com/flant/werf
https://github.com/owasp/www-pdf-archive
https://github.com/jaredwray/flat-cache
https://github.com/apache/uima-ducc
https://github.com/azure/azure-cosmosdb-python
https://github.com/apache/horaedb-client-rs
https://github.com/apache/seatunnel-website
https://github.com/azure/azure-sdk-for-java
https://github.com/openvinotoolkit/testrepo
https://github.com/sunpy/sunkit-spex
https://github.com/benmosher/eslint-plugin-import
https://github.com/werf/werf
https://github.com/genepattern/scgsea
https://github.com/louislam/uptime-kuma
https://github.com/18f/tlc-crew
https://github.com/kubernetes/kubernetes
https://github.com/geomscale/gsoc20
https://github.com/gnome/libgnomekbd
https://github.com/vmware/ansible-role-greengrass-awscli
https://github.com/vmware-archive/vmware-cloud-on-aws-sizing-powershell-script
https://github.com/apache/logging-flume-jms
https://github.com/apache/logging-flume-http
https://github.com/vmware-archive/ansible-role-microsoft-azure-iot
https://github.com/vmware/ansible-role-microsoft-azure-edge
https://github.com/apache/causeway-app-petclinic
https://github.com/vmware-samples/sonarqube-plugin-for-java
https://github.com/owasp/www-project-owasp-bcprivacy--the-owasp-privacy-toolkit
https://github.com/vmware/cloud-to-edge
https://github.com/geomscale/gsoc22
https://github.com/microsoft/microsoft-ignite-2022-after-parties
https://github.com/vmware/cloud-to-edge-automation
https://github.com/owasp/www-project-my-sample-documentation-project
https://github.com/nodejs/help
https://github.com/cubefs/cubefs
https://github.com/ansible/ansible
https://github.com/vmware/vcd-cli
https://github.com/cloud-gov/tooling
https://github.com/ansible/awx-resource-go-operator
https://github.com/redis/spring-batch-redis
https://github.com/mattwilkinsonn/aws-os-connection
https://github.com/thoth-station/prescriptions
https://github.com/microsoft/diffyconfiganalyzer
https://github.com/bbc/devx-templates
https://github.com/ome/snoopys-sandbox
https://github.com/gogs/go-gogs-client
https://github.com/intel/intel-operator-for-telegraf-agent
https://github.com/jakartaee/jaxb-api
https://github.com/jakartaee/saaj-api
https://github.com/jakartaee/jws-api
https://github.com/soulwallet/detect-gamestop-provider
https://github.com/getsentry/session-replay-analyzer
https://github.com/soulwallet/soul-wallet-corelib-deprecated
https://github.com/microsoft/iryonlp-mediqa-corr-2024
https://github.com/nietowilson/diabeticscol
https://github.com/clean-dependency-project/spring-framework-fnma53
https://github.com/clean-dependency-project/spring-framework-fnma53-web
https://github.com/ibm/sarama
https://github.com/cytoscape/legend-creator-new
https://github.com/bitnami/containers
https://github.com/tmpvar/defaults
https://github.com/digitalservicebund/govuk-design-system
https://github.com/microsoft/nl-partner-landing-page
https://github.com/digitalservicebund/platform-playground
https://github.com/digitalservicebund/ris-reports
https://github.com/openrewrite/rewrite-terraform
https://github.com/openrewrite/rewrite-nodejs
https://github.com/openrewrite/rewrite-ruby
https://github.com/openrewrite/rewrite-ai-search
https://github.com/betaflight/betaflight-pull-requests
https://github.com/kiegroup/wildfly
https://github.com/bengland2/automated_ceph_test
https://github.com/canonical/dotnet-ubuntu-helper
https://github.com/appscode/jsonpatch
https://github.com/smallnest/xdp
https://github.com/hhs/acf-ohsepr-dart-frontend
https://github.com/hhs/acf-ohsepr-dart-backend
https://github.com/cfpb/complaint-prototypes
https://github.com/microsoft/geneva
https://github.com/vmware-samples/vrealize-automation-content-generator
https://github.com/canonical/lxd-agent-loader
https://github.com/vmware/vcd-ext-sdk
https://github.com/hdrhistogram/hdrhistogram-go
https://github.com/warrant-dev/warrant-cloudflare-workers
https://github.com/scilifelabdatacentre/development-guidelines
https://github.com/nolimits4web/swiper
https://github.com/azure/azure-rest-api-specs
https://github.com/nats-io/nats.net
https://github.com/azure/azure-sdk-for-python
https://github.com/bengland2/backpack
https://github.com/scientific-python/blog.scientific-python.org-comments
https://github.com/microsoft/partner-center-billing-recon
https://github.com/sassoftware/edx-ora
https://github.com/sassoftware/rpath-xmllib
https://github.com/sassoftware/repodata
https://github.com/sassoftware/quickstart-sas-viya-gcp
https://github.com/sassoftware/wmiclient
https://github.com/sassoftware/virk
https://github.com/sassoftware/edx-demo-course
https://github.com/sassoftware/bigitr
https://github.com/scientific-python/nightly-wheels
https://github.com/sassoftware/sas-on-cf
https://github.com/sassoftware/quickstart-sas-viya-azure
https://github.com/sassoftware/restaf-graphql-demo
https://github.com/sassoftware/iot-enhanced-data-load-macro
https://github.com/grpc/grpc
https://github.com/cilium/cilium
https://github.com/distribution/distribution
https://github.com/daytonaio/daytona-aws-provider
https://github.com/hashicorp/vault
https://github.com/vmware-samples/cloud-director-service-migration
https://github.com/terra-money/terra-utils
https://github.com/department-of-veterans-affairs/ngl_north_dakota
https://github.com/daytonaio/core
https://github.com/daytonaio/daytona-podman-provider
https://github.com/quantecon/book-dp1
https://github.com/nats-io/gnatsd
https://github.com/openrewrite/rewrite-concourse
https://github.com/bengland2/benchmark-operator
https://github.com/alphagov/notifications-paas-route-service
https://github.com/milvus-io/milvus
https://github.com/netflix/eslint-config-netflix-dea
https://github.com/worldhealthorganization/push_to_emrs
https://github.com/department-of-veterans-affairs/ngl_rhode_island
https://github.com/near/docs-generator
https://github.com/department-of-veterans-affairs/ngl_south_carolina
https://github.com/gallowsdove/ostrava
https://github.com/aserto-dev/aserto-idp-plugin-azuread
https://github.com/paradigm4/faster_redimension
https://github.com/paradigm4/stream
https://github.com/aserto-dev/aserto-idp-plugin-json
https://github.com/aserto-dev/aserto-idp
https://github.com/aserto-dev/aserto-idp-plugin-okta
https://github.com/aserto-dev/aserto-go
https://github.com/paradigm4/finance
https://github.com/aserto-dev/idp-plugin-sdk
https://github.com/mikeal/request
https://github.com/scikit-hep/uproot4
https://github.com/worldhealthorganization/mnf-anthro-analyzer-offline
https://github.com/streamich/javascriptstuff-db
https://github.com/jaredwray/file-entry-cache
https://github.com/cnabio/cnab-go
https://github.com/streamich/rockey
https://github.com/department-of-veterans-affairs/vets-website
https://github.com/mattwilkinsonn/rust-claims
https://github.com/netflix/titus-controllers-api
https://github.com/gsa/beta-gsa
https://github.com/chromedp/sysutil
https://github.com/netflix/titus-resource-pool
https://github.com/ceph/ceph
https://github.com/ussba/reference-architecture
https://github.com/stolostron/acmqe-ci
https://github.com/ussba/aws-proton-sample-fargate-service
https://github.com/dotnet/docs
https://github.com/hashicorp/learn-terraform
https://github.com/bengland2/bohica
https://github.com/paradigm4/binary_load_example
https://github.com/airbytehq/airbyte
https://github.com/dotnet/fsharp-api-docs
https://github.com/dotnet/runtime
https://github.com/paradigm4/shift
https://github.com/paradigm4/limit
https://github.com/bengland2/cbt
https://github.com/airbytehq/stephane-airbyte
https://github.com/paradigm4/elastic_resource_groups
https://github.com/paradigm4/rv-stream
https://github.com/paradigm4/secure_scan
https://github.com/paradigm4/ganglia_python_modules
https://github.com/paradigm4/taq
https://github.com/paradigm4/scidb-shiny-auth
https://github.com/paradigm4/chunk_unique
https://github.com/paradigm4/nbbo-example
https://github.com/paradigm4/llsg
https://github.com/18f/polyfill-service
https://github.com/paradigm4/knn
https://github.com/paradigm4/grouped_aggregate
https://github.com/department-of-veterans-affairs/ngl_oregon
https://github.com/paradigm4/scidb-julia
https://github.com/paradigm4/scidb-tornado
https://github.com/paradigm4/load_tools
https://github.com/paradigm4/quotes
https://github.com/paradigm4/summarize
https://github.com/paradigm4/scidb-py
https://github.com/paradigm4/af
https://github.com/paradigm4/equi_join
https://github.com/paradigm4/basic_training
https://github.com/paradigm4/accelerated_io_tools
https://github.com/openshift/operator-framework-kapp-controller
https://github.com/allinopensource/emmaire-ahtunan
https://github.com/css-modules/icss-replace-symbols
https://github.com/cilium/ebpf.io-summit
https://github.com/allinopensource/passwordgenerator-mlh-ghw-2023
https://github.com/bitnami/arcanist-extensions
https://github.com/bitnami/azure-marketplace-charts
https://github.com/pivotal-cf/docs-pivotalcf-console
https://github.com/kubevirt/vmctl
https://github.com/openrewrite/rewrite-circleci
https://github.com/notaryproject/notation-go-lib
https://github.com/mongodb/terraform-provider-mongodbatlas-archive
https://github.com/intel/fineibt_testing
https://github.com/intel/esp-profile-redhat
https://github.com/intel/rpbs-telemetry
https://github.com/hhs/grants-api
https://github.com/intel/rpbs
https://github.com/intel/pretraining-with-intel-accelerators-gpu
https://github.com/gnome/gnome-common
https://github.com/pivotal-cf/docs-pcf-windows
https://github.com/alphagov/notifications-functional-tests-callback-app
https://github.com/pivotal-cf/docs-scheduler
https://github.com/pivotal-cf/docs-pas
https://github.com/pivotal-cf/docs-nist
https://github.com/18f/fleet
https://github.com/18f/draft-rfq-fns-nac
https://github.com/department-of-veterans-affairs/ngl-august-2015
https://github.com/department-of-veterans-affairs/nca-ngl-aug-2015
https://github.com/department-of-veterans-affairs/ngl_florida
https://github.com/department-of-veterans-affairs/ngl_georgia
https://github.com/department-of-veterans-affairs/caseflow-efolder
https://github.com/department-of-veterans-affairs/ngl_arkansas
https://github.com/department-of-veterans-affairs/ngl_kentucky
https://github.com/department-of-veterans-affairs/ngl_foreign_addresses
https://github.com/department-of-veterans-affairs/ngl_maryland
https://github.com/department-of-veterans-affairs/ngl_michigan
https://github.com/intel/perf-hfsort
https://github.com/department-of-veterans-affairs/ngl_missouri
https://github.com/vmware-archive/vsan-integration-for-prometheus
https://github.com/department-of-veterans-affairs/ngl-alabama
https://github.com/confluentinc/terraform-state-s3
https://github.com/department-of-veterans-affairs/ngl-arkansas
https://github.com/department-of-veterans-affairs/ngl-california
https://github.com/department-of-veterans-affairs/ngl-connecticut
https://github.com/pivotal-cf/docs-mysql-k8s
https://github.com/pivotal-cf/docs-csb-azure
https://github.com/pivotal-cf/docs-csb-aws
https://github.com/alphagov/special-route-publisher
https://github.com/department-of-veterans-affairs/ngl-indiana
https://github.com/department-of-veterans-affairs/ngl-iowa
https://github.com/department-of-veterans-affairs/jarranger-maven-plugin
https://github.com/vmware/upgrade-framework
https://github.com/department-of-veterans-affairs/ngl_minnesota
https://github.com/openela-main/perl-text-tabs-wrap
https://github.com/department-of-veterans-affairs/ngl-maine
https://github.com/vmware/cloud-to-edge-config-ui
https://github.com/vmware/cloud-director-ext-emulators
https://github.com/department-of-veterans-affairs/ngl-michigan
https://github.com/vmware-archive/photon-controller-go-sdk
https://github.com/department-of-veterans-affairs/ngl-nebraska
https://github.com/department-of-veterans-affairs/ngl-nevada
https://github.com/warrant-dev/plugin-image-zoom
https://github.com/vmware-archive/snapshot-diff-library
https://github.com/buildpacks/imgutil
https://github.com/warrant-dev/homebrew-warrant
https://github.com/warrant-dev/socal-infra-devtools-companies
https://github.com/hl7/fhir-us-pq-cmc-fda
https://github.com/apache/incubator-seatunnel-web
https://github.com/codedellemc/goscaleio
https://github.com/tootallnate/proxy-agents
https://github.com/geomscale/gsoc2021
https://github.com/vmware-labs/vms-for-slurm
https://github.com/aws/codewhisperer-command-line-discussions
https://github.com/apache/logging-flume-scribe
https://github.com/vmware-samples/people-counter-ingestion
https://github.com/apache/logging-flume-irc
https://github.com/vmware-archive/test-automation-for-web-applications
https://github.com/apache/logging-flume-twitter
https://github.com/openela-main/memtest86-
https://github.com/hl7/cda-ccda-2.1-sd
https://github.com/nodejs/node
https://github.com/microsoft/quic-offloads
https://github.com/quantecon/book-dp1-public
https://github.com/department-of-veterans-affairs/vets-api
https://github.com/getporter/porter
https://github.com/kubernetes/kubectl
https://github.com/operator-framework/operator-sdk
https://github.com/vmware/sql-to-dbsp-compiler
https://github.com/ansible/ansible-on-clouds-dev-docs
https://github.com/vmware-archive/cloud-automation-samples
https://github.com/thenativeweb/boolean
https://github.com/department-of-veterans-affairs/ruby-bgs
https://github.com/jakartaee/enterprise-beans
https://github.com/jakartaee/jax-ws-api
https://github.com/soulwallet/stackup-bundler
https://github.com/clean-dependency-project/spring-security53-fnma
https://github.com/k8snetworkplumbingwg/sriovnet
https://github.com/micro/network
https://github.com/elastic/beats
https://github.com/shahata/dasherize
https://github.com/openrewrite/rewrite-java-security
https://github.com/openrewrite/rules_rewrite
https://github.com/openrewrite/rewrite-migrate-python
https://github.com/apache/sdap-doms
https://github.com/vmware/bare-metal-server-integration-with-nsxt
https://github.com/ory/open-source-support
https://github.com/smallnest/mping
https://github.com/hashicorp/learn-terramino-digitalocean
https://github.com/sassoftware/rbm
https://github.com/sassoftware/bob-plans
https://github.com/sassoftware/spanner
https://github.com/sassoftware/intern
https://github.com/sassoftware/forester
https://github.com/helium/helium-foundation-terraform
https://github.com/sassoftware/discern
https://github.com/sassoftware/cs_comments_service
https://github.com/sassoftware/configuration
https://github.com/sassoftware/python-esppy
https://github.com/sassoftware/iot-ingest-data-into-cas-from-sas-esp
https://github.com/department-of-veterans-affairs/ngl_new_york
https://github.com/bengland2/badfish
https://github.com/renstrom/dedent
https://github.com/civicrm/civicrm-core
https://github.com/department-of-veterans-affairs/ngl_pennsylvania
https://github.com/department-of-veterans-affairs/ngl_south_dakota
https://github.com/department-of-veterans-affairs/ngl_tennessee
https://github.com/department-of-veterans-affairs/ngl_texas
https://github.com/department-of-veterans-affairs/ngl_usa_territoties
https://github.com/department-of-veterans-affairs/ngl_utah
https://github.com/carvel-dev/starlark-go
https://github.com/department-of-veterans-affairs/ngl_vermont
https://github.com/department-of-veterans-affairs/ngl_virginia
https://github.com/openshift/openshift-docs
https://github.com/department-of-veterans-affairs/ngl_washington
https://github.com/carvel-dev/difflib
https://github.com/alphagov/govwifi-concourse-deploy-pipeline
https://github.com/department-of-veterans-affairs/ngl_washingtondc
https://github.com/project-codeflare/integration-tests
https://github.com/department-of-veterans-affairs/ngl_wisconsin
https://github.com/department-of-veterans-affairs/ngl_wyoming
https://github.com/aserto-dev/aserto-idp-plugin-auth0
https://github.com/sinonjs/lolex
https://github.com/aserto-dev/aserto-idp-sync
https://github.com/aserto-dev/aserto-idp-seed
https://github.com/paradigm4/r_exec
https://github.com/dotnet/node-externals
https://github.com/jaegertracing/jaeger-client-go
https://github.com/openrewrite/rewrite-polyglot
https://github.com/openrewrite/rewrite-sql
https://github.com/bitnami/charts-docs
https://github.com/eclipse/tm
https://github.com/sassoftware/anaconda
https://github.com/vmware/clarity-assets
https://github.com/gnome/libgdamm
https://github.com/intel/mfit
https://github.com/intel/simics-fpga-examples
https://github.com/intel/rpbs-mips
https://github.com/intel/tdx-stacks
https://github.com/intel/mfit-storage-lib
https://github.com/bitnami/charts
https://github.com/vmware-archive/transport-go
https://github.com/vmware-archive/transport
https://github.com/gnome/gnome-modulesets
https://github.com/gnome/valadoc
https://github.com/pivotal-cf/docs-rabbitmq-pcf
https://github.com/pivotal-cf/docs-pcf-pws
https://github.com/okd-project/tekton-catalog
https://github.com/pivotal-cf/docs-addon-antivirus
https://github.com/pivotal-cf/docs-on-demand-service-broker
https://github.com/vmware-archive/vrealize-operations-customizations
https://github.com/pivotal-cf/docs-redis
https://github.com/pivotal-cf/docs-identity
https://github.com/pivotal-cf/docs-addon-ipsec
https://github.com/pivotal-cf/docs-mysql
https://github.com/mongodb/docs-shared
https://github.com/pivotal-cf/docs-gemfire-for-tas
https://github.com/alphagov/re-team-manual
https://github.com/pivotal-cf/docs-stemcell-rn
https://github.com/pivotal-cf/docs-tiledev
https://github.com/pivotal-cf/docs-metric-registrar
https://github.com/intel/x86s
https://github.com/bbc/dazzler-edit
https://github.com/department-of-veterans-affairs/ngl_alabama
https://github.com/department-of-veterans-affairs/ngl_arizona
https://github.com/department-of-veterans-affairs/techjam
https://github.com/department-of-veterans-affairs/ngl_colorado
https://github.com/department-of-veterans-affairs/ngl-alaska
https://github.com/department-of-veterans-affairs/ngl_california
https://github.com/department-of-veterans-affairs/ngl_delaware
https://github.com/department-of-veterans-affairs/ngl_mississippi
https://github.com/department-of-veterans-affairs/ngl_massachusetts
https://github.com/department-of-veterans-affairs/ngl_louisiana
https://github.com/department-of-veterans-affairs/ngl_hawaii
https://github.com/department-of-veterans-affairs/ngl_indiana
https://github.com/department-of-veterans-affairs/ngl_iowa
https://github.com/department-of-veterans-affairs/ngl_illinois
https://github.com/department-of-veterans-affairs/ngl_idaho
https://github.com/department-of-veterans-affairs/ngl_nevada
https://github.com/vmware-archive/transport-java
https://github.com/jetstack-experimental/cert-manager
https://github.com/department-of-veterans-affairs/ngl-alaska-
https://github.com/department-of-veterans-affairs/ngl-arizona-
https://github.com/pivotal-cf/docs-metric-store
https://github.com/pivotal-cf/docs-addon-compliance-tools
https://github.com/department-of-veterans-affairs/ngl-colorado
https://github.com/elastic/apm-pipeline-library-mp
https://github.com/department-of-veterans-affairs/ngl_gldelaware
https://github.com/department-of-veterans-affairs/ngl-foreign-addresses
https://github.com/department-of-veterans-affairs/ngl_-florida
https://github.com/elastic/elasticon
https://github.com/department-of-veterans-affairs/ngl-georgia
https://github.com/department-of-veterans-affairs/ngl-hawaii
https://github.com/department-of-veterans-affairs/ngl-idaho
https://github.com/department-of-veterans-affairs/ngl_illnois
https://github.com/vmware/copenapi
https://github.com/openshift/release
https://github.com/dotnet/roslyn
https://github.com/microsoft/unifiedlabelingsupporttool
https://github.com/department-of-veterans-affairs/ngl-kansas
https://github.com/alphagov/govuk-ruby
https://github.com/vmware/pyvcloud
https://github.com/openela-main/dvd-rw-tools
https://github.com/anaconda/terraform-aws-rds-cluster
https://github.com/vmware/ansible-aws-greengrass
https://github.com/department-of-veterans-affairs/ngl-maryland
https://github.com/vmware/ansible-module-vcloud-director
https://github.com/vmware/transport-typescript
https://github.com/pandas-dev/pandas
https://github.com/vmware/bitfusion-with-kubernetes-integration
https://github.com/microsoft/entra
https://github.com/cockroachdb/cockroach
https://github.com/graalvm/taming-build-time-initialization
https://github.com/enterprise-cmcs/mac-fc-security-hub-visibility-enterprise-jira
https://github.com/lark-parser/lark
https://github.com/department-of-veterans-affairs/ngl_new-hampshire
https://github.com/vmware/nerpa
https://github.com/npm/ini
https://github.com/junk1tm/musttag
https://github.com/department-of-veterans-affairs/ngl_new-mexico
https://github.com/department-of-veterans-affairs/ngl_west-virginia
https://github.com/department-of-veterans-affairs/ngl_south-dakota
https://github.com/department-of-veterans-affairs/ngl-wyoming
https://github.com/department-of-veterans-affairs/ngl-vermont
https://github.com/department-of-veterans-affairs/ngl-washingtondc
https://github.com/azure/dotnet-extensions-experimental
https://github.com/containers/libpod
https://github.com/sagold/gson-pointer
https://github.com/department-of-veterans-affairs/lombok-xjc-plugin
https://github.com/department-of-veterans-affairs/lighthouse-benefits-gateway-services
https://github.com/department-of-veterans-affairs/lighthouse-mock-benefits-gateway-services
https://github.com/department-of-veterans-affairs/health-apis-ids
https://github.com/department-of-veterans-affairs/lighthouse-veteran-verification
https://github.com/vmware-archive/vrealize-suite-lifecycle-manager-sdk
https://github.com/longhorn/samba
https://github.com/apcera/gnatsd
https://github.com/socketio/socket.io
https://github.com/vmware-archive/perl-net-sharepoint-basic
https://github.com/sourcegraph/sourcegraph
https://github.com/igraph/igraph.r-universe.dev
https://github.com/vmware-archive/ansible-role-cloud-to-edge-vm
https://github.com/vmware-labs/ui-guided-tours
https://gitlab.com/gitlab-org/gitlab
https://github.com/kkhaike/contextcheck
https://github.com/apache/logging-flume-morphline
https://github.com/vmware/service-level-indicator-exporter-for-kafka
https://github.com/soulwallet/bundler-server-deprecated
https://github.com/vmware/metadata-reaper-for-kafka
https://github.com/splice/sre-exercise
https://github.com/getsentry/answers
https://github.com/vmware-labs/build-inspector
https://github.com/elastic/elasticsearch
https://github.com/dotnet/sdk
https://github.com/elastic/kibana
https://github.com/clean-dependency-project/spring-framework53-fnma
https://github.com/huggingface/terraform-aws-vpc
https://github.com/datadog/datadog-agent
https://github.com/canonical/ubuntu-old-fashioned
https://github.com/gnome/gnome-nds-thumbnailer
https://github.com/gnome/at-spi2-atk
https://github.com/canonical/ubuntu-old-fashioned-1
https://github.com/microsoft/powerbi-visuals-utils-onobjectformatting
https://github.com/openrewrite/rewrite-kubernetes
https://github.com/openrewrite/rewrite-github-actions
https://github.com/cosmos/cosmos-brand-guide
https://github.com/smallnest/breakdown
https://github.com/smallnest/mping-rs
https://github.com/kiegroup/incubator-kie-tools
https://github.com/vmware/database-stream-processor
https://github.com/kiwix/kiwix-android-nightly
https://github.com/npm/inflight
https://github.com/hibernate/dtd
https://github.com/aws/aws-sdk-cpp
https://github.com/vmware/rules_oss_audit
https://github.com/microsoft/regla
https://github.com/sassoftware/edx-platform
https://github.com/sassoftware/rpath-models
https://github.com/kubernetes/website
https://github.com/sassoftware/ease
https://github.com/sassoftware/jobmaster
https://github.com/sassoftware/xqueue
https://github.com/kubernetes/test-infra
https://github.com/sassoftware/restaf-uicomponents
https://github.com/sassoftware/quickstart-sas-viya
https://github.com/sassoftware/jobslave
https://github.com/sassoftware/edx-theme
https://github.com/serverless-devs/core
https://github.com/sassoftware/unravl
https://github.com/sassoftware/bob
https://github.com/sassoftware/appengine
https://github.com/sassoftware/xml_resources
https://github.com/sassoftware/activate
https://github.com/sassoftware/visual-analytics-sdk
https://github.com/sassoftware/vdmml-trials-challenge
https://github.com/sassoftware/quickstart-sas-viya-common
https://github.com/sassoftware/restaf-apiexplorer
https://github.com/sassoftware/quickstart-sas-grid
https://github.com/sassoftware/restaf-graphql-server
https://github.com/vmware/nsx-integration-for-openshift
https://github.com/sassoftware/iot-esp-and-omnio-integration
https://github.com/sassoftware/iot-load-data-to-cas-using-mas
https://github.com/curiefense/curiefense
https://github.com/desmondsanctity/circe-klinikos
https://github.com/permify/permify-swagger
https://github.com/department-of-veterans-affairs/ngl_north_carolina
https://github.com/department-of-veterans-affairs/ngl_ohio
https://github.com/quantecon/book-networks
https://github.com/hashicorp/learn-terraform-cloud
https://github.com/parallel-fs-utils/fio
https://github.com/department-of-veterans-affairs/ngl_oklahoma
https://github.com/worldhealthorganization/ems2-common-services
https://github.com/department-of-veterans-affairs/ngl_west_virginia
https://github.com/aserto-dev/aserto-idp-plugin-aserto
https://github.com/paradigm4/de_rle
https://github.com/bengland2/benchmark-wrapper
https://github.com/streamich/p4-ui
https://github.com/go-chassis/paas-lager
https://github.com/failsafe787/bittyrant
https://github.com/kubevirt/kvm-info-nfd-plugin
https://github.com/intel/tdx-tools
https://github.com/gnome/buoh
https://github.com/vmware-archive/vrops-restapi-samples
https://github.com/vmware-archive/date-and-time-pattern-detection
https://github.com/okd-project/moc
https://github.com/pivotal-cf/docs-aws-services
https://github.com/okd-project/okd-operator-index
https://github.com/pivotal-cf/docs-metrics
https://github.com/pivotal-cf/docs-addon-fim
https://github.com/okd-project/rhel-edge-automation-arch
https://github.com/pivotal-cf/docs-ops-manager
https://github.com/pivotal-cf/docs-vmware-harbor
https://github.com/vmware-archive/clarity-city
https://github.com/pivotal-cf/docs-operating-pas
https://github.com/vmware-archive/image-relocation
https://github.com/department-of-veterans-affairs/connect_vbms
https://github.com/department-of-veterans-affairs/ngl_connecticut
https://github.com/department-of-veterans-affairs/ngl-aug-2015
https://github.com/department-of-veterans-affairs/ngl_new_mexico
https://github.com/department-of-veterans-affairs/caseflow
https://github.com/department-of-veterans-affairs/ngl_kansas
https://github.com/department-of-veterans-affairs/ngl_maine
https://github.com/department-of-veterans-affairs/ngl_montana
https://github.com/department-of-veterans-affairs/ngl_nebraska
https://github.com/department-of-veterans-affairs/ngl_new_hampshire
https://github.com/department-of-veterans-affairs/ngl_new_jersey
https://github.com/vmware-archive/wavefront-plugin-for-jenkins
https://github.com/vmware-archive/nerpa
https://github.com/python/cpython
https://github.com/pivotal-cf/docs-mysql-pas
https://github.com/pivotal-cf/docs-spring-cloud-dataflow-k8s
https://github.com/pivotal-cf/docs-build-service
https://github.com/pivotal-cf/docs-csb-gcp
https://github.com/mongodb/terraform-mongodbatlas-modules
https://github.com/department-of-veterans-affairs/ngl-delaware
https://github.com/microsoft/windows-sandbox-utilities
https://github.com/grafana/grafana
https://github.com/hashicorp/terraform-provider-aws
https://github.com/openela-main/dbus-c-
https://github.com/quarkusio/quarkus
https://github.com/azure/azure-sdk-for-net
https://github.com/cmsgov/serverless-iam-helper
https://github.com/department-of-veterans-affairs/ngl-kentucky
https://github.com/microsoft/c2pa-content-credentials-validator
https://github.com/microsoft/woodgrove-music
https://github.com/department-of-veterans-affairs/ngl-louisiana
https://github.com/vmware/o11n-plugin-crypto
https://github.com/department-of-veterans-affairs/ngl-massachusetts
https://github.com/graalvm/3rd-parties
https://github.com/openela-main/libsigc-20
https://github.com/vmware/vmware-cloud-director-ui-components
https://github.com/vmware/vmaccel
https://github.com/department-of-veterans-affairs/ngl-minnesota
https://github.com/department-of-veterans-affairs/ngl-mississippi
https://github.com/department-of-veterans-affairs/ngl-montana
https://github.com/vmware/cloud-director-typescript-clients
https://github.com/department-of-veterans-affairs/ngl-missouri
https://github.com/department-of-veterans-affairs/ngl_new-york
https://github.com/lerna/lerna
https://github.com/bengland2/ceph-linode
https://github.com/department-of-veterans-affairs/ngl_new-jersey
https://github.com/go-chassis/openlog
https://github.com/fanniemaeopensource/university-of-maryland-bitcamp-2023-challenge
https://github.com/vmware-labs/repository-editor-for-tuf
https://github.com/department-of-veterans-affairs/ngl-texas
https://github.com/department-of-veterans-affairs/ngl_rhode-island
https://github.com/department-of-veterans-affairs/ngl-washington
https://github.com/inspect-js/has-symbols
https://github.com/department-of-veterans-affairs/ngl-tennessee
https://github.com/renekroon/ttlcache
https://github.com/prometheus-operator/prometheus-operator
https://github.com/vmware-labs/api-data-collector
https://github.com/facebookincubator/create-react-app
https://github.com/department-of-veterans-affairs/caseflow-monitor
https://github.com/broofa/node-mime
https://github.com/armosec/go-git-url
https://github.com/openai/bchess-personal
https://github.com/department-of-veterans-affairs/design-system
https://github.com/department-of-veterans-affairs/developer-portal
https://github.com/department-of-veterans-affairs/appeals-devops-jenkins
https://github.com/department-of-veterans-affairs/lighthouse-vulcan
https://github.com/department-of-veterans-affairs/va.gov-team
https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records
https://github.com/department-of-veterans-affairs/swagger-examples-maven-plugin
https://github.com/department-of-veterans-affairs/lighthouse-facilities
https://github.com/department-of-veterans-affairs/lighthouse-callculon
https://github.com/department-of-veterans-affairs/lighthouse-mock-emis
https://github.com/microsoft/gestures-samples
https://github.com/apache/fury
https://github.com/eclipse-ee4j/jsp-api
https://github.com/cloudhealth/activerecord-mysql-reconnect
https://github.com/googlei18n/libphonenumber
https://github.com/sunpy/sunxspex
https://github.com/dsacms/party-planning-website
https://github.com/greenplum-db/plcontainer
https://github.com/greenplum-db/pivotalr
https://github.com/greenplum-db/gporca
https://github.com/greenplum-db/gp-stream-server-plugin
https://github.com/greenplum-db/gpbackup
https://github.com/greenplum-db/greenplum-release-engineering-libraries
https://github.com/greenplum-db/greenplum-for-kubernetes
https://github.com/greenplum-db/filedump
https://github.com/greenplum-db/pgbouncer
https://github.com/greenplum-db/go-gpdb
https://github.com/greenplum-db/greenplumr
https://github.com/ebay/homereplication
https://github.com/ornl/fdms_poc
https://github.com/alphagov/pay-frontend-with-percy-testing
https://github.com/ray-project/ray
https://github.com/gnome/libgrss
https://github.com/gnome/grilo-mediaserver2
https://github.com/gnome/libgtkmusic
https://github.com/gnome/gnome-ostree-integration
https://github.com/gnome/chronojump-web
https://github.com/gnome/gst-debugger
https://github.com/gnome/libgfbgraph
https://github.com/gnome/gnome-shell-sass
https://github.com/gsa/odp-tf-google-sql
https://github.com/gsa/odp-forseti-constraint-library
https://github.com/gsa/odp-cf-service-catalog
https://github.com/gsa/odp-tf-gcp-stackdriver
https://github.com/gsa/odp-lqtmtest
https://github.com/gsa/odp-tf-aws-ref-arch-waf-regional
https://github.com/redhat-developer/che-dockerfiles
https://github.com/redhat-developer/che-functional-tests
https://github.com/redhatinsights/snow-service-graph-connector-rh-insights
https://github.com/bengland2/une_stats
https://github.com/bengland2/dpdk-pingpong
https://github.com/bengland2/jetpack
https://github.com/redhat-developer/codeready-workspaces-deprecated
https://github.com/openzipkin-contrib/zipkin-go-opentracing
https://github.com/postmanlabs/open-technologies-docs
https://github.com/fedora-infra/resultsdb-operator
https://github.com/carpentries/docs.carpentries.org
https://github.com/department-of-veterans-affairs/ruby_claim_evidence_api
https://github.com/department-of-veterans-affairs/mhv-fhir-phr-mapping
https://github.com/vectordotdev/regex
https://github.com/docker/go
https://github.com/bbc/matterhorn
https://github.com/bbc/pan-bbc-churn-predictions
https://github.com/bbc/iplayer-web-code-pipeline-prototype
https://github.com/microsoft/dataactivator
https://github.com/microsoft/commercial-marketplace-meters-accelerator
https://github.com/microsoft/adaptivecloudlab-tf
https://github.com/microsoft/woodgrove-vid
https://github.com/microsoft/vscode-azure-agent
https://github.com/kubewarden/gtmpl-rust
https://github.com/octoprint/pre-commit-hooks
https://github.com/confidential-containers/cloud-providers
https://github.com/confidential-containers/peerpod-ctrl
https://github.com/confidential-containers/peerpodconfig-ctrl
https://github.com/kcl-lang/kcl-java
https://github.com/kcl-lang/kcl-js
https://github.com/azure/azure-cosmos-table-python
https://github.com/gsa/edx
https://github.com/open-cluster-management-io/governance-policy-template-sync-archive
https://github.com/open-cluster-management-io/governance-policy-nucleus
https://github.com/gsa/livebooks
https://github.com/microsoft/mcw-app-modernization
https://github.com/microsoft/mcw-building-a-resilient-iaas-architecture
https://github.com/microsoft/mcw-intelligent-analytics
https://github.com/azure/on-demand-capacity-reservation
https://github.com/azure/azureml-snippets
https://github.com/microsoft/mobile-chest-x-ray-analysis
https://github.com/microsoft/intune-powershell-management
https://github.com/keycloak/keycloak-demo
https://github.com/keycloak/keycloak-ui
https://github.com/keycloak/keycloak-rest-api-description
https://github.com/keycloak/keycloak-gh-actionbot
https://github.com/open-telemetry/opentelemetry-collector-contrib
https://github.com/jaegertracing/jaeger-lib
https://github.com/azure/azure-docs-sdk-dotnet.zh-tw
https://github.com/azure/azure-docs-sdk-dotnet.de-de
https://github.com/azure/azure-docs-sdk-dotnet.ja-jp
https://github.com/azure/azure-docs-sdk-dotnet.nl-nl
https://github.com/azure/azure-docs-sdk-dotnet.es-es
https://github.com/azure/azure-docs-sdk-dotnet.sv-se
https://github.com/azure/cachebrowns
https://github.com/azure/terraform-azure-azureacademy-avd-lab
https://github.com/azure/accelerator-spring-apps
https://github.com/azure/osdu-bicep
https://github.com/azure/gpt_ale
https://github.com/azure/wordpress-on-linux-app-service-plugins
https://github.com/azure/set
https://github.com/microsoft/vcpkg
https://github.com/microsoft/dscconfiguration.tests
https://github.com/microsoft/dscconfiguration.template
https://github.com/microsoft/msccl-scheduler
https://github.com/microsoft/devazureciv
https://github.com/microsoft/vs-intellicode
https://github.com/microsoft/businesscentralhelloworld.appsource
https://github.com/microsoft/orchestrator
https://github.com/microsoft/mcw-sap-plus-extend-and-innovate-with-data-and-ai
https://github.com/microsoft/mcw-ai-led-business-process-automation
https://github.com/microsoft/brainstorm-fluidframework-m365-azure
https://github.com/microsoft/omnichannel-chat-sdk-samples
https://github.com/microsoft/react-swa-workshop-template
https://github.com/microsoft/demosaicer
https://github.com/microsoft/azure-data-services-go-fast-codebase-es-dlz
https://github.com/microsoft/partnercenter-gdaptransition
https://github.com/microsoft/mcw-building-the-business-migration-case-with-linux-and-oss-db-to-azure
https://github.com/microsoft/mcw-building-the-business-migration-case-with-windows-server-and-sql-server
https://github.com/microsoft/kvs-rc-migration-web-orchestrator
https://github.com/cmsgov/serverless-idempotency-helper
https://github.com/graalvm/syft
https://github.com/fanniemaeopensource/hackudt-2023
https://github.com/joyent/node-http-signature
https://github.com/department-of-veterans-affairs/ngl_north-carolina
https://github.com/department-of-veterans-affairs/ngl-wisconsin
https://github.com/confluentinc/yum-s3-iam
https://github.com/graalvm/downloads
https://github.com/department-of-veterans-affairs/ngl_north-dakota
https://github.com/department-of-veterans-affairs/ngl-rhode-island
https://github.com/department-of-veterans-affairs/ngl-oregon
https://github.com/department-of-veterans-affairs/ngl-ohio
https://github.com/department-of-veterans-affairs/ngl-oklahoma
https://github.com/department-of-veterans-affairs/ngl-pennsylvania
https://github.com/department-of-veterans-affairs/ngl-utah
https://github.com/department-of-veterans-affairs/ngl-virginia
https://github.com/moby/spdystream
https://github.com/department-of-veterans-affairs/ngl_south-carolina
https://github.com/department-of-veterans-affairs/ngl_usa-territoties
https://github.com/department-of-veterans-affairs/caseflow-commons
https://github.com/module-federation/core
https://github.com/tannerlinsley/react-query
https://github.com/department-of-veterans-affairs/caseflow-frontend-toolkit
https://github.com/sagold/gson-query
https://github.com/jdx/go-netrc
https://github.com/dfcreative/color-name
https://github.com/isaacs/abbrev-js
https://github.com/azure/responsible-ai-hub
https://github.com/department-of-veterans-affairs/health-apis-mock-eligibility-and-enrollment
https://github.com/department-of-veterans-affairs/health-apis-aws-interfaces
https://github.com/department-of-veterans-affairs/health-apis-conformance-unifier
https://github.com/department-of-veterans-affairs/health-apis-community-care-eligibility
https://github.com/department-of-veterans-affairs/lighthouse-docserver
https://github.com/alphagov/pay-egress
https://github.com/department-of-veterans-affairs/health-apis-data-query
https://github.com/department-of-veterans-affairs/redacted-public-release-bms-v3-v2.4-iter-4-oct-2019
https://github.com/commaai/agnos
https://github.com/azure/c2pa-rs
https://github.com/department-of-veterans-affairs/redacted-public-release-bms-v4-webb_2_21-build-1-mar-2021
https://github.com/department-of-veterans-affairs/lighthouse-oauth-proxy
https://github.com/pivotal/docs-cluster-essentials
https://github.com/warrant-dev/templates
https://github.com/vmware-samples/accessibility-visual-report
https://github.com/vmware-samples/webassembly-browser-apps
https://github.com/willf/bitset
https://github.com/grafana/cognito-idpool-auth
https://github.com/cloudhealth/puppet-rest
https://github.com/department-of-veterans-affairs/lighthouse-maven-starter
https://github.com/department-of-veterans-affairs/safe-settings
https://github.com/scikit-hep/uproot3
https://github.com/alphagov/di-ipv-cri-fraud-api
https://github.com/cds-snc/terraform-aws-control_tower_account_factory
https://github.com/vmware-tanzu/buildkit-cli-for-kubectl
https://github.com/pingcap/tidb
https://github.com/alphagov/di-ipv-core-tests
https://github.com/alphagov/gdx-vision-prototypes
https://github.com/alphagov/test-repo-chris
https://github.com/alphagov/learningtime-jy-sem1
https://github.com/alphagov/di-account-rad
https://github.com/eclipse-ee4j/saaj-api
https://github.com/greenplum-db/gp-xerces
https://github.com/greenplum-db/geospatial
https://github.com/greenplum-db/greenplum-db-for-debian
https://github.com/greenplum-db/.github
https://github.com/digitalservicebund/digitalcheck-tool-finder
https://github.com/gnome/seed
https://github.com/gsa/searchgov-docker
https://github.com/gnome/gnome-internet-radio-locator
https://github.com/gnome/perl-gtk2
https://github.com/apache/incubator-horaedb-client-java
https://github.com/apache/activemq-artemis-console-plugin
https://github.com/sassoftware/content-sdk
https://github.com/bengland2/touchstone
https://github.com/department-of-veterans-affairs/appeals-consumer
https://github.com/elastic/sast-pov-cloud-on-k8s
https://github.com/vectordotdev/tcp_server
https://github.com/vectordotdev/docusaurus
https://github.com/osohq/zanzibar
https://github.com/osohq/repository-api-oso-authorization
https://github.com/nlnetlabs/draft-koekkoek-dnsop-zone-file-format
https://github.com/dragonflyoss/backend
https://github.com/microsoft/tokenmixers
https://github.com/curiefense/curiefense-gitbook
https://github.com/curiefense/media
https://github.com/microsoft/turkana-grid-mapping
https://github.com/keycloak/kcinit
https://github.com/keycloak/keycloak-playground
https://github.com/kcl-lang/kcl-dotnet
https://github.com/kcl-lang/app2kube
https://github.com/kcl-lang/mindwm-gitops-kcl
https://github.com/microsoft/mcw-microservices-architecture
https://github.com/microsoft/mcw-serverless-architecture
https://github.com/microsoft/mcw-continuous-delivery-in-azure-devops
https://github.com/microsoft/mcw-modern-cloud-apps
https://github.com/microsoft/mcw-big-data-analytics-and-visualization
https://github.com/microsoft/mcw-sql-server-hybrid-cloud
https://github.com/microsoft/mcw-oss-devops
https://github.com/microsoft/mcw-enterprise-ready-cloud
https://github.com/microsoft/mcw-azure-blockchain
https://github.com/microsoft/brokered-winrt-components
https://github.com/microsoft/mcw-mobile-app-innovation
https://github.com/microsoft/mcw
https://github.com/microsoft/exchangegroupmigration
https://github.com/microsoft/mcw-high-performance-computing
https://github.com/microsoft/mcw-business-continuity-and-disaster-recovery
https://github.com/microsoft/mcw-analyzing-text-with-azure-machine-learning-and-cognitive-services
https://github.com/open-telemetry/opentelemetry-profiling
https://github.com/azure/fta-enterprisereadystorage
https://github.com/containerd/cri
https://github.com/microsoft/mcw-cosmos-db-real-time-advanced-analytics
https://github.com/microsoft/autoseg-monai-himl
https://github.com/azure/fta-japan
https://github.com/azure/azure-appservices-diagnostics-kustoingestor
https://github.com/azure/avdblueprint
https://github.com/azure/arc-vmm-arm-rest
https://github.com/azure/azure-docs-sdk-dotnet.fr-fr
https://github.com/azure/azure-docs-sdk-dotnet.hu-hu
https://github.com/azure/azure-docs-sdk-dotnet.pt-pt
https://github.com/azure/azure-docs-sdk-dotnet.tr-tr
https://github.com/azure/azure-docs-sdk-dotnet.bg-bg
https://github.com/azure/azure-docs-sdk-dotnet.ar-sa
https://github.com/azure/azure-docs-sdk-dotnet.en-sg
https://github.com/azure/noopsaccelerator
https://github.com/azure/external-metrics-injestion-agent
https://github.com/microsoft/mwt-ds-louiemart
https://github.com/microsoft/applicationinsights-python
https://github.com/microsoft/partsunlimited
https://github.com/microsoft/fluentui
https://github.com/microsoft/windows-ping
https://github.com/microsoft/pstn-callrecord-plan-alerts
https://github.com/microsoft/a_comparative_study_of_llm_based_conversational_semantic_parsing
https://github.com/saltstack/salt
https://github.com/microsoft/vscode-azure-blockchain-ethereum
https://github.com/saltstack/vsphere-automation-sdk-python
https://github.com/saltstack/pytest-coverage-contexts
https://github.com/saltstack/salt-pack
https://github.com/microsoft/fr-dai-team-portal
https://github.com/microsoft/mcw-machine-learning
https://github.com/microsoft/mcw-real-time-data-with-azure-database-for-postgresql-hyperscale
https://github.com/microsoft/mcw-modernizing-data-analytics-with-sql-server-2019
https://github.com/microsoft/mcw-ml-ops
https://github.com/microsoft/aspnetcore-react-webapp
https://github.com/microsoft/winget-pkgs
https://github.com/microsoft/mcw-predictive-maintenance-for-remote-field-devices
https://github.com/microsoft/datascience4managers
https://github.com/microsoft/mcw-hybrid-identity
https://github.com/microsoft/servicefabricdsc
https://github.com/microsoft/commercial-marketplace-saas-manual-on-boarding
https://github.com/microsoft/mcw-azure-synapse-analytics-and-ai
https://github.com/microsoft/commercial-marketplace-client-python
https://github.com/microsoft/winui-3-demos
https://github.com/microsoft/robust-models-transfer
https://github.com/microsoft/mcw-innovate-and-modernize-apps-with-data-and-ai
https://github.com/microsoft/mcw-implementing-azure-virtual-desktop-in-the-enterprise
https://github.com/microsoft/fundraising-and-engagement
https://github.com/microsoft/dynamics-365-fraud-protection-manualreview
https://github.com/microsoft/azure_spatial_anchors_ros
https://github.com/microsoft/lsg-python-brownbag
https://github.com/microsoft/commercial-marketplace-samples
https://github.com/microsoft/cbl-marinervulnerabilitydata
https://github.com/microsoft/mcw-leveraging-azure-digital-twins-in-a-supply-chain
https://github.com/microsoft/deepdevdocs
https://github.com/microsoft/swagger-ui
https://github.com/microsoft/edge-device-image-builder-public-preview
https://github.com/microsoft/customdpp
https://github.com/microsoft/autopredoptconnector
https://github.com/microsoft/kiota-http-guzzle-php
https://github.com/microsoft/vscode-merge-editor-dev-companion
https://github.com/microsoft/sql-migration-azuresql-poc
https://github.com/cmsgov/serverless-s3-bucket-helper
https://github.com/google/evergreen-checker
https://github.com/xgi/streamlink
https://github.com/skypy/cloaked-octo-sansa
https://github.com/mdanalysis/mdanalysistutorial
https://github.com/skypy/sample
https://github.com/skypy/blue
https://github.com/pyvista/pyvista-gmsh
https://github.com/econ-ark/remark-starter-example
https://github.com/scikit-hep/uproot5
https://github.com/cdcgov/erhms-info-manager
https://github.com/conda-forge/numpy-sugar-feedstock
https://github.com/hhs/eis-pmo-inventorytracking
https://github.com/azure/azure-docs
https://github.com/saltstack/relative-environment-for-python
https://github.com/jakartaee/transactions
https://github.com/microsoft/arbutus
https://github.com/chaoss/wg-metrics-development
https://github.com/graphql-kit/graphql-voyager
https://github.com/azure/terraform-azurerm-avm-ptn-alz
https://github.com/microsoft/iqengine
https://github.com/microsoft/mcw-azure-stack
https://github.com/jakartaee/authentication
https://github.com/flant/kubedog
https://github.com/containernetworking/cni
https://github.com/bytecodealliance/rsix
https://github.com/k8snetworkplumbingwg/multus-cni
https://github.com/bitinn/node-fetch
https://github.com/containerd/ttrpc
https://github.com/eclipse-ee4j/jaspic
https://github.com/alphagov/platforms-product-page
https://github.com/apache/incubator-celeborn-website
https://github.com/apache/celeborn-website
https://github.com/gruntwork-io/go-commons
https://github.com/badging/badging
https://github.com/isaacs/ignore-walk
https://github.com/cenkalti/backoff
https://github.com/eclipse-ee4j/ejb-api
https://github.com/vmware-archive/sql-to-dbsp-compiler
https://github.com/aws/amazon-ecs-shim-loggers-for-containerd
https://github.com/cfpb/website-indexer
https://github.com/jakartaee/connectors
https://github.com/saltstack/salt-auto-pack
https://github.com/vmware-archive/vcd-ext-sdk
https://github.com/jakartaee/pages
https://github.com/jakartaee/expression-language
https://github.com/azure/appcat-rulesets
https://github.com/eclipse-ee4j/jaxb-api
https://github.com/microsoft/anyonecancode
https://github.com/vmware-archive/vcd-ext-samples
https://github.com/akihirosuda/sshocker
https://github.com/azure/azure-iot-operations
https://github.com/deislabs/smi-sdk-go
https://github.com/k0kubun/pp
https://github.com/gsa/datagov-harvesting-logic
https://github.com/cenk/backoff
https://github.com/cncf-tags/container-device-interface
https://github.com/gnome/gedit-plugins
https://github.com/gnome/atk
https://github.com/owasp/www-project-zap
https://github.com/azure/flux2-gitops
https://github.com/pivotal/docs-credhub-service-broker
https://github.com/pivotal/tpc-ds
https://github.com/department-of-veterans-affairs/lighthouse-auth-utils
https://github.com/department-of-veterans-affairs/lighthouse-starter-datamart
https://github.com/grafana/grafana-ci-config
https://github.com/vmware-samples/people-counter-engagement
https://github.com/vmware-samples/vcd-ext-samples
https://github.com/cloudhealth/ar-ondemand
https://github.com/apache/horaedb-client-py
https://github.com/opentofu/homebrew-opentofu
https://github.com/grafana/adaptive-metrics-autoapply-action
https://github.com/cloudhealth/threatstack-chef
https://github.com/spring-cloud/spring-cloud-jenkins-jobs
https://github.com/cloudhealth/terraform-cloudhealth-iam
https://github.com/bokeh/distributed
https://github.com/department-of-veterans-affairs/lighthouse-saml-utils
https://github.com/cockroachdb/molt
https://github.com/department-of-veterans-affairs/sparkcql
https://github.com/postman-open-technologies/gsoc-2024
https://github.com/eclipse-uprotocol/up-client-sommr-rust
https://github.com/eclipse-uprotocol/up-client-zenoh-java
https://github.com/hewlettpackard/docker-machine-oneview
https://github.com/fixie-ai/fixie-sdk-python
https://github.com/greenplum-db/gpbackup-s3-plugin
https://github.com/greenplum-db/plr
https://github.com/greenplum-db/diskquota
https://github.com/greenplum-db/greenplum-database-release
https://github.com/canonical/nrpe-charm
https://github.com/noaa-orr-erd/mapbox_earcut-feedstock
https://github.com/systemd/systemd
https://github.com/gsa/odp-tf-google-monitoring
https://github.com/gsa/odp-tf-aws-ref-arch-ec2
https://github.com/gsa/less-rails-bootstrap
https://github.com/gsa/odp-tf-aws-ref-arch-vpc
https://github.com/rust-lang/rust
https://github.com/redhatinsights/patchman-engine-deps
https://github.com/redhat-developer/devspaces-theia
https://github.com/bengland2/jetski
https://github.com/bengland2/linode_api4-python
https://github.com/bengland2/magazine
https://github.com/bengland2/ocp4_upi_baremetal
https://github.com/bengland2/openshift-accessories
https://github.com/bengland2/openstack-osd-discovery
https://github.com/bengland2/pbench
https://github.com/bengland2/scale-ci-deploy
https://github.com/bengland2/stockpile
https://github.com/elastic/sast-pov-beats
https://github.com/fedora-infra/automate-packaging-tracker
https://github.com/graalvm/scaladays2018-demos
https://github.com/elastic/sast-pov-kibana2
https://github.com/redhat-developer/codeready-workspaces-operator
https://github.com/osohq/oso-browser-quickstart
https://github.com/linux-application-whitelisting/fapolicyd-performance
https://github.com/microsoft/cimetrics
https://github.com/microsoft/al-go-pte-pppreview
https://github.com/microsoft/shadow-alignment-mia
https://github.com/microsoft/microsoftlearnstudentambassadors
https://github.com/curiefense/curiefense.github.io
https://github.com/curiefense/curiefense-helm
https://github.com/microsoft/azure-chat-with-your-photos-demo
https://github.com/microsoft/turkana-camp-roof-mapping
https://github.com/werf/kubedog
https://github.com/opcr-io/oras-go
https://github.com/servicemeshinterface/smi-sdk-go
https://github.com/gsa/rpa_test
https://github.com/gsa/staging-review
https://github.com/microsoft/mcw-template-cloud-workshop
https://github.com/microsoft/mcw-internet-of-things
https://github.com/microsoft/mcw-intelligent-vending-machines
https://github.com/microsoft/mcw-cloud-native-applications
https://github.com/microsoft/mcw-migrating-oracle-to-azure-sql-and-postgresql
https://github.com/microsoft/mcw-optimized-architecture
https://github.com/microsoft/mcw-migrate-edw-to-azure-sql-data-warehouse
https://github.com/microsoft/mcw-sap-netweaver-on-azure
https://github.com/microsoft/mcw-oss-paas-and-devops
https://github.com/microsoft/mcw-sap-hana-on-azure
https://github.com/microsoft/mcw-iot-and-the-smart-city
https://github.com/microsoft/mcw-securing-paas
https://github.com/microsoft/mcw-security-baseline-on-azure
https://github.com/microsoft/mcw-linux-lift-and-shift
https://github.com/microsoft/mcw-windows-server-and-sql-server-2008-r2-end-of-support-planning
https://github.com/azure/adl-rules-template
https://github.com/azure/projectluna
https://github.com/azure/codegenapp
https://github.com/azure/guardrailssolutionaccelerator
https://github.com/azure/azure-rest-api-specs-2
https://github.com/azure/azure-functions-jupyter-worker
https://github.com/azure/aks-tls-bootstrap
https://github.com/azure/eraser-scanner-template
https://github.com/azure/ap5gc-partner-tools
https://github.com/azure/opentelemetry-demo
https://github.com/azure/mtm-tech-enablement-labs
https://github.com/microsoft/moodle
https://github.com/microsoft/vscode
https://github.com/microsoft/availability-monitor-for-kafka
https://github.com/microsoft/experfanalyzer
https://github.com/microsoft/botbuilder-location
https://github.com/microsoft/homebrew-mssql-preview
https://github.com/microsoft/homebrew-msodbcsql-test
https://github.com/microsoft/mcw-securing-azure-iot-solutions
https://github.com/microsoft/start-cpuburn
https://github.com/microsoft/mcw-migrating-sql-databases-to-azure
https://github.com/microsoft/agieval
https://github.com/microsoft/fr-dai-hol-iac
https://github.com/microsoft/naturallanguageprogram
https://github.com/microsoft/mcw-line-of-business-application-migration
https://github.com/microsoft/cela-tag-processing-service
https://github.com/microsoft/commercial-marketplace-client-node
https://github.com/microsoft/digitaljustice
https://github.com/microsoft/azhcicss
https://github.com/microsoft/waflab
https://github.com/microsoft/ossarium
https://github.com/microsoft/waflab-hyperscan-test
https://github.com/microsoft/defender-connect
https://github.com/microsoft/fast-cli
https://github.com/cmsgov/macpro-quickstart-serverless-infra
https://github.com/microsoft/security-devops-policy
https://github.com/saltstack/pr-comments-test
https://github.com/cmsgov/ab2d-bcda-sample-python-fhirconnectathon-july2023
https://github.com/enterprise-cmcs/palet
https://github.com/google/taglesscrm
https://github.com/pytorch/pytorch
https://github.com/sunpy/gallery
https://github.com/sunpy/conda-sync
https://github.com/hhs/dscolab---spring-2020-cohort
https://github.com/belaban/ironjacamar
https://github.com/department-of-veterans-affairs/tech-jam-2013---islington-green
https://github.com/paradigm4/wearable_prototypes
https://github.com/microsoft/cbl-mariner
https://github.com/reacttraining/react-router
https://github.com/iarna/unique-slug
https://github.com/jakartaee/websocket
https://github.com/microsoft/azurelinux
https://github.com/apache/logging-flume-legacy
https://github.com/uber/jaeger-lib
https://github.com/appc/cni
https://github.com/container-orchestrated-devices/container-device-interface
https://github.com/azure/aks-hybrid
https://github.com/cfpb/design-stories
https://github.com/microsoft/api-extractor.com-website
https://github.com/eclipse-ee4j/common-annotations-api
https://github.com/coreos/dex
https://github.com/huggingface/lm-evaluation-harness
https://github.com/microsoft/azure-openai-dev-skills-orchestrator
https://github.com/microsoft/security-utilities
https://github.com/npm/abbrev-js
https://github.com/wildfly-security/wildfly-elytron-ee
https://github.com/serverless-devs/s-core
https://github.com/docker/cnab-to-oci
https://github.com/eclipse-ee4j/jca-api
https://github.com/daytonaio/docs
https://github.com/azure/windup-rulesets
https://github.com/microsoft/appinsights-python
https://github.com/google/model-transparency
https://github.com/isaacs/node-tar
https://github.com/nats-io/nats.net.v2
https://github.com/redis/rueidis
https://github.com/cryostatio/cryostat3
https://github.com/microsoft/commercial-marketplace-solutions
https://github.com/aws/aws-record-ruby
https://github.com/azure/terraform-azurerm-alz
https://github.com/openzipkin/zipkin-go-opentracing
https://github.com/microsoft/everyonecancode
https://github.com/openelb/openelb
https://github.com/scientific-python/cookie
https://github.com/google/earthengine-api
https://github.com/antonmedv/expr
https://github.com/jakartaee/common-annotations-api
https://github.com/department-of-veterans-affairs/ves-event-bus-developer-portal
https://github.com/scikit-hep/repo-review
https://github.com/apache/incubator-kvrocks-website
https://github.com/microsoft/powervirtualagentssamples
https://github.com/eclipse-ee4j/el-ri
https://github.com/azure/aksarc
https://github.com/awslabs/smithy-go
https://github.com/azure/azure-mobile-apps
https://github.com/microsoft/officecppguidelines
https://github.com/department-of-veterans-affairs/tech-jam-2013---rambo-tango-panda-
https://github.com/npm/mute-stream
https://github.com/lima-vm/sshocker
https://github.com/go-simpler/musttag
https://github.com/apache/sdap-ingester
https://github.com/microsoft/windows-ai-studio
https://github.com/microsoft/azurelinux-tutorials
https://github.com/microsoft/blueprints
https://github.com/owasp/owasp-vwad
https://github.com/kubernetes-sigs/gateway-api
https://github.com/microsoft/applicationinsights-dotnet
https://github.com/microsoft/web-build-tools
https://github.com/microsoft/monaco-editor
https://github.com/heyxyz/hey
https://github.com/improbable-eng/thanos
https://github.com/coreos/operator-sdk
https://github.com/googleapis/sdk-platform-java
https://github.com/ysurac/openmptcprouter
https://github.com/vmware/govmomi
https://github.com/docker/kitematic
https://github.com/heptio/contour
https://github.com/jetstack/cert-manager
https://github.com/alphagov/govwifi-admin
https://github.com/reduxjs/redux
https://github.com/confluentinc/librdkafka
https://github.com/scilifelabdatacentre/kiarva-frontend
https://github.com/smallnest/iptv
https://github.com/microsoft/reactors
https://github.com/azure/azure-iot-mobility-digitaltwin
https://github.com/gnome/gnome-themes-extra
https://github.com/gsa/odp-vulnerablewebapp
https://github.com/gnome/glade
https://github.com/sassoftware/hq
https://github.com/elastic/sast-pov-kibana-h1
https://github.com/department-of-veterans-affairs/tech-jam-2013---team-double-impact
https://github.com/nasa/now-in-space
https://github.com/azure/azure-ai-model-catalog
https://github.com/azure/mqttbrokerprivatepreview
https://github.com/microsoft/techcasestudies
https://github.com/department-of-veterans-affairs/health-apis-fhir-resources
https://github.com/microsoft/mcw-enterprise-class-networking
https://github.com/department-of-veterans-affairs/health-apis-kong
https://github.com/department-of-veterans-affairs/health-apis-eligibility-and-enrollment-client
https://github.com/streamich/glamorous
https://github.com/vmware-archive/bridgeql
https://github.com/vmware-labs/wasm-languages
https://github.com/census-instrumentation/opencensus-java
https://github.com/vmware-archive/octant
https://github.com/vmware/test-operations
https://github.com/vmware/safekeeping
https://github.com/vitessio/vitess
https://github.com/azure/azure-cli-extensions
https://github.com/azure/azure-powershell-1
https://github.com/azure/azure-ai-content-safety-private-preview
https://github.com/masterminds/goutils
https://github.com/vmware-archive/metadata-reaper-for-kafka
https://github.com/microsoft/powerbi-visuals-utils-onobjectutils
https://github.com/vmware-archive/cloud-director-service-migration
https://github.com/vmware-archive/people-counter-engagement
https://github.com/microsoft/kiota-serialization-json-php
https://github.com/sindresorhus/strip-eof
https://github.com/azure/azure-center-for-sap-solutions-preview
https://github.com/ben-eb/cssnano
https://github.com/cssnano/cssnano
https://github.com/gsa/ansible-os-ubuntu22
https://github.com/vmware/vsan-integration-for-prometheus
https://github.com/k14s/starlark-go
https://github.com/vmware-samples/cloud-automation-samples
https://github.com/cdd/cdd-terraform-aws-atlantis
https://github.com/skypy/bootstrap
https://github.com/apache/manifoldcf-integration-solr-9x
https://github.com/aws/q-command-line-discussions
https://github.com/ethstorage/chains
https://github.com/apache/flume-site
https://github.com/hl7/cardx-ig
https://github.com/apache/seatunnel-shade
https://github.com/apache/incubator-seatunnel-shade
https://github.com/apache/logging-flume-spring-boot
https://github.com/vmware-labs/date-and-time-pattern-detection
https://github.com/vmware-archive/upgrade-framework
https://github.com/vmware-archive/api-data-collector
https://github.com/apache/sdap-website
https://github.com/vmware/photon-controller-go-sdk
https://github.com/apache/logging-flume-search
https://github.com/vmware-archive/cloud-to-edge-config-ui
https://github.com/quantecon/dp_text_website
https://github.com/scientific-python/devstats-data
https://github.com/enterprise-cmcs/mac-fc-security-hub-visibility
https://github.com/uber/jaeger-client-go
https://github.com/apache/logging-flume-jdbc
https://github.com/jakartaee/servlet
https://github.com/azure/azure-kusto-opentelemetry-demo
https://github.com/microsoft/few_shot_adaptation_for_parsing_contextual_utterances_with_llms
https://github.com/coreos/bugs
https://github.com/crossplane/crossplane
https://github.com/enterprise-cmcs/serverless-waf-plugin
https://github.com/apache/infrastructure-duo_unix
https://github.com/azure/external-metrics-ingestion-agent
https://github.com/knq/sysutil
https://github.com/apache/logging-flume-hadoop
https://github.com/microsoft/supervisord-watchdog
https://github.com/department-of-veterans-affairs/tech-jam-2013---ibm-federal
https://github.com/paradigm4/sg_free_cross_between
https://github.com/go-mesh/openlogging
https://github.com/envoyproxy/envoy
https://github.com/apache/logging-flume-site
https://github.com/akka/akka-persistence-dynamodb
https://github.com/paradigm4/arrayopr
https://github.com/jdxcode/netrc
https://github.com/microsoft/visnet
https://github.com/mswjs/headers-polyfill
https://github.com/microsoft/net-offloads
https://github.com/hl7/cda-ccda
https://github.com/apache/fury-site
https://github.com/gsa/datagov-harvester-airflow
https://github.com/jfrazelle/go
https://github.com/overture-stack/dms-ui
https://github.com/azure/azure-vm-utils
https://github.com/apache/seatunnel-datasource-sdk
https://github.com/azure/msccl-scheduler
https://github.com/apache/sdap-ningester
https://github.com/microsoft/aks-hci-apps
https://github.com/microsoft/terminal
https://github.com/vmware/clarity-city
https://github.com/sindresorhus/strip-final-newline
https://github.com/vmware-archive/rules_oss_audit
https://github.com/mrrio/jspdf
https://github.com/apache/sdap-ningesterpy
https://github.com/alphagov/di-report-a-death
https://github.com/cenk1cenk2/listr2
https://github.com/jakartaee/mail-api
https://github.com/googleapis/gapic-generator-java
https://github.com/statelyai/xstate
https://github.com/gengo/grpc-gateway
https://github.com/microsoft/powerbi-report-authoring
https://github.com/microsoft/cluster-api-inplace-upgrader
https://github.com/microsoft/azure_arc_community
https://github.com/kubescape/go-git-url
https://github.com/microsoft/powerbi-client-vue-js
https://github.com/microsoft/cluster-api-inplace-updater
https://github.com/microsoft/facesynthetics
https://github.com/google/rust-crate-audits
https://github.com/vmware-archive/vivace
https://github.com/microsoft/powerbi-client-angular
https://github.com/microsoft/vscode-gulp-electron
https://github.com/servicecomb/paas-lager
https://github.com/econ-ark/estimatingmicrodsops
https://github.com/qutip/qutip-qoc
https://github.com/vmware-archive/nsx-integration-for-openshift
https://github.com/microsoft/adaptive_cloud_community
https://github.com/canonical/haproxy-operator
https://github.com/sciml/neuraloperators.jl
https://github.com/vmware/transport-go
https://github.com/apache/incubator-horaedb-client-rs
https://github.com/css-modules/icss-utils
https://github.com/apache/incubator-seatunnel-website
https://github.com/azure/sonic-buildimage-msft
https://github.com/18f/approaches
https://github.com/microsoft/microsft-purview-advanced-rich-reports-mparr-collector
https://github.com/department-of-veterans-affairs/tech-jam-2013---team-11
https://github.com/department-of-veterans-affairs/tech-jam-2013---vcare
https://github.com/department-of-veterans-affairs/tech-jam-fall-2013---awesome-nighthawks
https://github.com/microsoft/mcw-media-ai
https://github.com/gogits/go-gogs-client
https://github.com/cfpb/crawsqueal
https://github.com/cnabio/cnab-to-oci
https://github.com/apache/skywalking-kubernetes
https://github.com/jakartaee/jaf-api
https://github.com/tc39/source-map-rfc
https://github.com/eclipse-ee4j/jacc
https://github.com/nats-io/nats.js
https://github.com/gsa/datagov-harvester
https://github.com/eclipse-ee4j/jta-api
https://github.com/jakartaee/validation
https://github.com/gnome/gedit
https://github.com/gnome/tracker
https://github.com/vmware-archive/buildkit-cli-for-kubectl
https://github.com/microsoft/confidential-sidecar-containers
https://github.com/npm/unique-slug
https://github.com/docker/spdystream
https://github.com/microsoft/vscode-ai-toolkit
https://github.com/npm/ignore-walk
https://github.com/greenplum-db/gpdb
https://github.com/paradigm4/shim
https://github.com/microsoft/azure-data-services-go-fast-codebase
https://github.com/microsoft/azure-quickstart-templates
https://github.com/huggingface/peft
https://github.com/getsentry/sentry-cli
https://github.com/hhs/simpler-grants-gov
https://github.com/google/instrumentation-java
https://github.com/rancher/submariner
https://github.com/thanos-io/thanos
https://github.com/docker/hub-feedback
https://github.com/apache/kvrocks
https://github.com/lensterxyz/lenster
https://github.com/dragonflyoss/dragonfly2
https://github.com/linkerd/linkerd2
https://github.com/go-redis/redis
https://github.com/microsoft/rushstack
https://github.com/huggingface/accelerate
https://github.com/hashicorp/vscode-terraform
https://github.com/mongodb/laravel-mongodb
https://github.com/module-federation/universe
https://github.com/azure/azureml-assets
https://github.com/dexidp/dex
https://github.com/davidkpiano/xstate
https://github.com/datawire/ambassador
https://github.com/chubaofs/chubaofs
https://github.com/openmicroscopy/openmicroscopy
https://github.com/microsoft/live-share
https://github.com/aws/aws-sdk-php
https://github.com/flant/dapp
https://github.com/cytoscape/cytoscape.js
https://github.com/lucas-clemente/quic-go
https://github.com/redhat-developer/vscode-java
https://github.com/alauda/kube-ovn
https://github.com/oauth2-proxy/oauth2-proxy
https://github.com/quic-go/quic-go
https://github.com/getsentry/publish
https://github.com/nats-io/nats-server
https://github.com/gogf/gf
https://github.com/zeromicro/go-zero
https://github.com/crossplaneio/crossplane
https://github.com/argoproj/argo-workflows
https://github.com/dragonflyoss/dragonfly
https://github.com/mikro-orm/mikro-orm
https://github.com/argoproj/argo
https://github.com/aws/karpenter-provider-aws
https://github.com/getsentry/scratch.codecov-flakiness
https://github.com/fedora-infra/fedora-college
https://github.com/kcl-lang/kcl-py
https://github.com/department-of-veterans-affairs/tech-jam-2013---cognizant
https://github.com/department-of-veterans-affairs/tech-jam-2013---team-dbgt-cary
https://github.com/microsoft/forecasting
https://github.com/paradigm4/pkgdown
https://github.com/definitelytyped/definitelytyped
https://github.com/kubernetes/deployment-manager
https://github.com/vmware/ansible-security-hardening
https://github.com/azure/c2pa-js
https://github.com/bokeh/blog.bokeh.org
https://github.com/bbc/programmes-preview
https://github.com/gnome/gdl
https://github.com/greenplum-db/pljava
https://github.com/gnome/gnome-mud
https://github.com/paradigm4/bridge
https://github.com/aws/aws-sdk-java
https://github.com/apache/incubator-horaedb-client-py
https://github.com/vmware-archive/inclusive-language-ext-for-sonarqube
https://github.com/hl7/standard-patient-health-record-ig
https://github.com/aokoli/goutils
https://github.com/vmware/go-reminders
https://github.com/vmware/vivace
https://github.com/moby/libnetwork
https://github.com/denis-tingaikin/go-header
https://github.com/vmware/vhpc-toolkit
https://github.com/rust-lang/pin-utils
https://github.com/blosc/blosc2-btune
https://github.com/microsoft/tes-azure
https://github.com/facebook/jest
https://github.com/protocolbuffers/protobuf
https://github.com/camunda-cloud/zeebe
https://github.com/microsoft/-azure-data-services-go-fast-codebase-es-dmz
https://github.com/ebay/zeta
https://github.com/scilifelabdatacentre/kiarva-backend
https://github.com/vmware-archive/copenapi
https://github.com/vmware-archive/ansible-role-greengrass-awscli
https://github.com/k14s/difflib
https://github.com/vmware-archive/vms-for-slurm
https://github.com/keybase/go-keychain
https://github.com/aws/shim-loggers-for-containerd
https://github.com/buildpack/imgutil
https://github.com/azure/ap5gc-vendor-tools
https://github.com/containerd/cri-containerd
https://github.com/theupdateframework/notary
https://github.com/enterprise-cmcs/macpro-quickstart-serverless-infra
https://github.com/apache/logging-flume-kafka
https://github.com/apache/incubator-horaedb-docs
https://github.com/microsoft/qdk-python
https://github.com/cryostatio/cryostat
https://github.com/deislabs/oras
https://github.com/vmware-archive/sonarqube-plugin-for-java
https://github.com/canonical/ubuntu-security-guide
https://github.com/vmware-archive/cloud-to-edge-automation
https://github.com/vmware-archive/webassembly-browser-apps
https://github.com/vmware/wavefront-plugin-for-jenkins
https://github.com/eraser-dev/eraser-scanner-template
https://github.com/notaryproject/notation-go
https://github.com/keycloak/keycloak-k8s-resources
https://github.com/deislabs/porter
https://github.com/enterprise-cmcs/serverless-idempotency-helper
https://github.com/microsoft/security-devops-rules
https://github.com/konveyor/tackle2-operator
https://github.com/vmware-archive/vmware-cloud-director-ui-components
https://github.com/microsoft/powerapps-language-tooling
https://github.com/enterprise-cmcs/serverless-iam-helper
https://github.com/vmware-archive/o11n-plugin-crypto
https://github.com/google/supply-chain
https://github.com/microsoft/copilotstudiosamples
http://github.com/bioconductor/bbs
https://github.com/vmware-archive/clarity-assets
https://github.com/thanos-community/promql-engine
https://github.com/enterprise-cmcs/amazon-ecs-run-task
https://github.com/apache/incubator-sdap-website
https://github.com/scikit-hep/cookie
https://github.com/apache/pulsar-presto
https://github.com/kubernetes-client/python
https://github.com/runconduit/conduit
https://github.com/kubernetes/helm
https://github.com/microsoft/electionguard-egvote
https://github.com/lithammer/dedent
https://github.com/jellydator/ttlcache
https://github.com/mswjs/node-request-interceptor
https://github.com/submariner-io/submariner
https://github.com/vmware-archive/vrealize-automation-content-generator
https://github.com/vmware-archive/bare-metal-server-integration-with-nsxt
https://github.com/vmware-archive/cloud-director-ext-emulators
https://github.com/microsoft/security-devops-common
https://github.com/hashicorp/learn-terraform-cloud-variable-sets
https://github.com/alphagov/di-rad-prototypes
https://github.com/vmware/transport-java
https://github.com/zephyrproject-rtos/kconfiglib
https://github.com/cmsgov/serverless-waf-plugin
https://github.com/vmware-archive/ansible-aws-greengrass
https://github.com/blosc/blosc2_btune
https://github.com/vmware-archive/go-reminders
https://github.com/microsoft/vscode-entra-externalid
https://github.com/isaacs/mute-stream
https://github.com/konveyor/operator
https://github.com/apache/paimon-website
https://github.com/vmware-archive/wasm-languages
https://github.com/sagold/json-pointer
https://github.com/vmware/transport
https://github.com/vmware-labs/inclusive-language-ext-for-sonarqube
https://github.com/isaacs/inflight
https://github.com/ljharb/has-symbols
https://github.com/mdanalysis/mdahole2
https://github.com/broofa/mime
https://github.com/sylvia7788/contextcheck
https://github.com/econ-ark/solvingmicrodsops-lifecycle
https://github.com/aws/aws-prototyping-sdk
https://github.com/google/new-project
https://github.com/opencontainers/runtime-spec
https://github.com/grpc-ecosystem/grpc-gateway
https://github.com/longhorn/types
https://github.com/alexcrichton/jobserver-rs
https://github.com/mswjs/interceptors
https://github.com/gregberge/svgr
https://github.com/smartystreets/assertions
https://github.com/microsoft/vcpkg-ce-catalog
https://github.com/isaacs/node-which
https://github.com/pulp/pulp-ui
https://github.com/google/bulk_fhir_tools
https://github.com/eclipse-ee4j/jax-ws-api
https://github.com/department-of-veterans-affairs/design-system-old
https://github.com/eclipse-ee4j/security-api
https://github.com/microsoft/azure-openai-design-patterns
https://github.com/openjdk/jdk
https://github.com/microsoft/azure-quantum-python
https://github.com/eclipse-ee4j/mail
https://github.com/kube-rs/kube
https://github.com/dotnet/aspnetdocs
https://github.com/goharbor/harbor
https://github.com/containers/podman
https://github.com/projectatomic/libpod
https://github.com/mui/material-ui
https://github.com/helium/helium-foundation-k8s
https://github.com/hashicorp/terraform-provider-azurerm
https://github.com/jenkinsci/code-coverage-api-plugin
https://github.com/enterprise-cmcs/mac-fc-amazon-ecs-run-task
https://github.com/bytecodealliance/rustix
https://github.com/apache/.github
https://github.com/node-fetch/node-fetch
https://github.com/alphagov/govwifi-tech-docs
https://github.com/enterprise-cmcs/mako
https://github.com/sagemath/sage
https://github.com/colorjs/color-name
https://github.com/microsoft/ospo-courses
https://github.com/redhat-developer/red-hat-developers-documentation-rhdh
https://github.com/spack/spack
https://github.com/googleapis/gnostic
https://github.com/sonic-net/sonic-buildimage-msft
https://github.com/vmware/harbor
https://github.com/sindresorhus/node-defaults
https://github.com/cloud-gov/bosh-deployment-resource
https://github.com/bbc/viewporter
https://github.com/microsoft/dotnet-framework-early-access
https://github.com/luin/ioredis
https://github.com/google/libphonenumber
https://github.com/elastic/wordlake-staging
https://github.com/devspace-sh/devspace
https://github.com/department-of-veterans-affairs/lighthouse-platform-backend
https://github.com/request/request
https://github.com/tanstack/query
https://github.com/spring-projects/spring-boot
https://github.com/microsoft/powertoys
https://github.com/paradigm4/dev_tools
https://github.com/urfave/cli
https://github.com/azure/azure-nvme-utils
https://github.com/vmware-archive/repository-editor-for-tuf
https://github.com/npm/unique-filename
https://github.com/microsoft/tsdoc.org-website
https://github.com/microsoft/windows-sandbox
https://github.com/apache/datafusion-ballista-python
https://github.com/opencontainers/specs
https://github.com/kubernetes-sigs/karpenter
https://github.com/mswjs/headers-utils
https://github.com/mellanox/sriovnet
https://github.com/flant/logboek
https://github.com/kubesphere/porter
https://github.com/rust-lang/rustc-demangle
https://github.com/oras-project/oras
https://github.com/hl7/fhir-us-pq-cmc
https://github.com/apcera/nats
https://github.com/alexcrichton/rustc-demangle
https://github.com/apache/horaedb-client-java
https://github.com/codegangsta/cli
https://github.com/eclipse-ee4j/glassfish
https://github.com/moby/moby
https://github.com/microsoft/azurelinuxvulnerabilitydata
https://github.com/backstage/backstage
https://github.com/sociallycompute/update-test
https://github.com/hl7/cardx-htn-mng
https://github.com/18f/guides
https://github.com/jestjs/jest
https://github.com/apache/incubator-pekko-persistence-r2dbc
https://github.com/azure/azure-powershell
https://github.com/crossplane/crossplane-runtime
https://github.com/azure/azure-center-for-sap-solutions
https://github.com/apache/sdap-in-situ-data-services
https://github.com/vmware-tanzu/octant
https://github.com/denis-tingajkin/go-header
https://github.com/vmware-archive/test-operations
https://github.com/pivotal/image-relocation
https://github.com/mui-org/material-ui
https://github.com/blosc/caterva2
https://github.com/google/medical_claims_tools
https://github.com/k14s/ytt
https://github.com/thecodeteam/goscaleio
https://github.com/azure/mtm-labs
https://github.com/apache/datafusion-python
https://github.com/rust-lang-nursery/pin-utils
https://github.com/smallrye/smallrye-reactive-utils
https://github.com/microsoft/powerbi-client-react
https://github.com/smarty/assertions
https://github.com/kube-rs/kube-rs
https://github.com/bbc/branding-client
https://github.com/werf/logboek
https://github.com/armon/go-metrics
https://github.com/jenkinsci/cobertura-plugin
https://github.com/department-of-veterans-affairs/cql-transpiler
https://github.com/saltstack/salt-pack-py3
https://github.com/microsoft/adaptive-testing
https://github.com/apache/arrow-datafusion-python
https://github.com/nodejitsu/node-http-proxy
https://github.com/notaryproject/notary
https://github.com/apache/incubator-horaedb-client-go
https://github.com/microsoft/microsoft-purview-advanced-rich-reports-mparr-collector
https://github.com/mdanalysis/hole2-mdakit
https://github.com/jakartaee/authorization
https://github.com/stevvooe/ttrpc
https://github.com/saltstack/relenv
https://github.com/vmware-archive/ansible-security-hardening
https://github.com/aws/amazon-q-connectjs
https://github.com/vmware/bridgeql
https://github.com/vmware-archive/database-stream-processor
https://github.com/rueian/rueidis
https://github.com/carvel-dev/ytt
https://github.com/alexcrichton/cfg-if
https://github.com/microsoft/project-oagents
https://github.com/apache/incubator-sdap-ingester
https://github.com/enterprise-cmcs/macpro-mako
https://github.com/smooth-code/svgr
https://github.com/cmsgov/hpt-tool
https://github.com/azure/eraser
https://github.com/apache/horaedb-client-go
https://github.com/kubernetes-sigs/service-apis
https://github.com/eclipse-ee4j/jws-api
https://github.com/pyvista/pyvista-posters
https://github.com/rust-lang/jobserver-rs
https://github.com/apache/horaedb-docs
https://github.com/microsoft/kiota-authentication-phpleague-php
https://github.com/bits-and-blooms/bitset
https://github.com/scientific-python/repo-review
https://github.com/apache/seatunnel-web
https://github.com/scientific-python/pytest-doctestplus
https://github.com/apache/sdap-nexus
https://github.com/alphagov/govwifi-dev-docs
https://github.com/enterprise-cmcs/serverless-s3-bucket-helper
https://github.com/microsoft/ics-forensics-tools
https://github.com/tootallnate/node-https-proxy-agent
https://github.com/docker/distribution
https://github.com/kiegroup/optaplanner-quickstarts
https://github.com/sagold/json-query
https://github.com/vmware-archive/salt-pack
https://github.com/apache/incubator-fury
https://github.com/grafana/mimir
https://github.com/crossplaneio/crossplane-runtime
https://github.com/apache/incubator-horaedb
https://github.com/nats-io/nats
https://github.com/docker/notary
https://github.com/bitnami/vms
https://github.com/microsoft/vscode-go
https://github.com/aws/aws-sdk-net
https://github.com/projectcontour/contour
https://github.com/coreos/prometheus-operator
https://github.com/aws/karpenter
https://github.com/blosc/caterva
https://github.com/carpentries/handbook-beta
https://github.com/eclipse-ee4j/websocket-api
https://github.com/microsoft/adaptivecards
https://github.com/helm/helm
https://github.com/apache/sdap-nexusproto
https://github.com/apache/incubator-sdap-nexusproto
https://github.com/vmware-archive/cloud-director-typescript-clients
https://github.com/isaacs/ini
https://github.com/jakartaee/security
https://github.com/sympy/sympy
https://github.com/matplotlib/matplotlib
https://github.com/docker/docker
https://github.com/microsoft/vscode-ms-entra
https://github.com/cri-o/cri-o
https://github.com/greenplum-db/pxf
https://github.com/microsoft/openocd
https://github.com/aws/aws-cdk
https://github.com/dotnet/corefx
https://github.com/openshift/origin
https://github.com/gravitational/teleport
https://github.com/alphagov/open-data-certificate
https://github.com/microsoft/docs
https://github.com/leanprover-community/mathlib4
https://github.com/paradigm4/orderbook-example
https://github.com/paradigm4/scripts
https://github.com/bokeh/badges
https://github.com/elastic/apm-server-1
https://github.com/aws/sagemaker-xgboost-container
https://github.com/zephyrproject-rtos/hal_espressif
https://github.com/microsoft/linux-tracer
https://github.com/google/it-cert-automation-practice
https://github.com/bokeh/bokeh-scala-sample
https://github.com/skypy/fullstack-vue
https://github.com/mdanalysis/mdanalysiscookbook
https://github.com/sunpy/sunpy-bot
https://github.com/sunpy/gallery_old
https://github.com/sunpy/old-package-template
https://github.com/sunpy/azure-pipelines-template
https://github.com/cisagov/ansible-role-pypy
https://github.com/cisagov/setup-packer
https://github.com/cisagov/ansible-role-disable-thp
https://github.com/cdcgov/covid19-rt
https://github.com/cdcgov/data-exchange-devops
https://github.com/hhs/fda-everytrycounts
https://github.com/bengland2/ceph
https://github.com/microsoft/mcw-azure-security-and-management
https://github.com/bokeh/bokehplots.com
https://github.com/microsoft/mcw-lift-and-shift-azure-resource-manager
https://github.com/skypy/dracula-theme
https://github.com/apache/incubator-fury-site
https://github.com/iarna/unique-filename
https://github.com/tritondatacenter/node-http-signature
https://github.com/codemirror/codemirror
https://github.com/microsoft/wsl
https://github.com/remix-run/react-router
https://github.com/seaweedfs/seaweedfs
https://github.com/vmware-archive/ansible-module-vcloud-director
https://github.com/apache/datafusion-comet
https://github.com/envoyproxy/protoc-gen-validate
https://github.com/lyft/protoc-gen-validate
https://github.com/apache/datafusion-ballista
https://github.com/apache/arrow-datafusion-comet
https://github.com/astropy/pytest-doctestplus
https://github.com/deislabs/cnab-go
https://github.com/microsoft/kiota-abstractions-php
https://github.com/scikit-hep/uproot
https://github.com/microsoft/activemlp
https://github.com/kubernetes-sigs/cri-o
https://github.com/gruntwork-io/gruntwork-cli
https://github.com/tmzane/musttag
https://github.com/aws/aws-sdk-ruby-record
https://github.com/sigstore/model-transparency
https://github.com/pyvista/scikit-gmsh
https://github.com/sinonjs/fake-timers
https://github.com/vmware-archive/vcd-cli
https://github.com/expr-lang/expr
https://github.com/coreos/bbolt
https://github.com/microsoft/finops-toolkit
https://github.com/eclipse-ee4j/servlet-api
https://github.com/aws/aws-pdk
https://github.com/alphagov/govwifi-authentication-api
https://github.com/gsa/site-scanning-engine
https://github.com/debug-js/debug
https://github.com/eraser-dev/eraser
https://github.com/bioconductor/bbs
https://github.com/apache/arrow-ballista
https://github.com/streamxhub/streamx
https://github.com/paradigm4/collate
https://github.com/gnome/tracker-miners
https://github.com/intel/fineibt_glibc
https://github.com/sassoftware/azure-quickstart-templates
https://github.com/greenplum-db/gpupgrade
https://github.com/apache/parquet-java
https://github.com/evanw/esbuild
https://github.com/ome/openmicroscopy
https://github.com/fluent/fluentd
https://github.com/popperjs/popper-core
https://github.com/microsoft/psrule-vscode
https://github.com/import-js/eslint-plugin-import
https://github.com/spring-projects/spring-session
https://github.com/huggingface/text-generation-inference
https://github.com/apache/incubator-kvrocks
https://github.com/floating-ui/floating-ui
https://github.com/redis/go-redis
https://github.com/covexo/devspace
https://github.com/redhatinsights/insights-core
https://github.com/docker/libnetwork
https://github.com/vmware-archive/vhpc-toolkit
https://github.com/microsoft/azureadexporter
https://github.com/google/cluster-data
https://github.com/microsoft/window-post-message-proxy
https://github.com/microsoft/spfx-gulp-tools
https://github.com/microsoft/ai2bmd
https://github.com/apache/dubbo-python
https://github.com/listr2/listr2
https://github.com/tonistiigi/fifo
https://github.com/apache/sdap-mudrod
https://github.com/vmware-archive/pyvcloud
https://github.com/apache/incubator-paimon-website
https://github.com/alphagov/ckanext-spatial
https://github.com/apache/sdap-edge
https://github.com/vmware-archive/safekeeping
https://github.com/microsoft/woodgrove-music-android
https://github.com/inclavare-containers/secure-ai
https://github.com/microsoft/tes-azure-legacy
https://github.com/gomodules/jsonpatch
https://github.com/microsoft/rushstack-legacy
https://github.com/vmware-archive/bitfusion-with-kubernetes-integration
https://github.com/rust-lang/cfg-if
https://github.com/hashicorp/go-metrics
https://github.com/npm/node-tar
https://github.com/vmware-archive/service-level-indicator-exporter-for-kafka
https://github.com/ivangoncharov/graphql-voyager
https://github.com/microsoft/powerbi-jupyter
https://github.com/codahale/hdrhistogram
https://github.com/containerd/fifo
https://github.com/microsoft/playwright-github-action
https://github.com/apache/kvrocks-website
https://github.com/apache/incubator-sdap-nexus
https://github.com/scikit-learn/scikit-learn
https://github.com/saltstack/salt-ci-images
https://github.com/vmware-archive/build-inspector
https://github.com/aws/amazon-connect-wisdomjs
https://github.com/microsoft/adatest
https://github.com/microsoft/cbl-marinertutorials
https://github.com/eclipse-ee4j/jaf
https://github.com/visionmedia/debug
https://github.com/numpy/numpy
https://github.com/gsa/federal-website-index
https://github.com/microsoft/entraexporter
https://github.com/apache/skywalking-helm
https://github.com/xenolf/lego
https://github.com/valkey-io/valkey-glide
https://github.com/azure/azure-cli
https://github.com/vmware-archive/transport-typescript
https://github.com/microsoft/power-bi-embedded-contoso-sales-demo
https://github.com/microsoft/azure-genai-design-patterns
https://github.com/pyvista/pyvista-poster
https://github.com/npm/node-which
https://github.com/chaoss/wg-common
https://github.com/erezsh/lark
https://github.com/chubaofs/cfs
https://github.com/microsoft/ms-dos
https://github.com/facebook/react
https://github.com/smallrye/smallrye-mutiny-vertx-bindings
https://github.com/dotnet/versions
https://github.com/buildpack/pack
https://github.com/dotnet/efcore
https://github.com/intel/multus-cni
https://github.com/buildpacks/lifecycle
https://github.com/apache/horaedb
https://github.com/azure/azure-docs-powershell-azuread
https://github.com/twall/jna
https://github.com/aws/karpenter-core
https://github.com/microsoft/ospo
https://github.com/apache/pekko-persistence-r2dbc
https://github.com/go-acme/lego
https://github.com/apache/parquet-mr
https://github.com/cert-manager/cert-manager
https://github.com/microsoft/aks-arc-apps
https://github.com/vmware-archive/accessibility-visual-report
https://github.com/google/fuchsiaware
https://github.com/google/protobuf
https://github.com/redis/ioredis
https://github.com/aws/glide-for-redis
https://github.com/shopify/sarama
https://github.com/neovim/neovim
https://github.com/hashicorp/terraform
https://github.com/keycloak/keycloak
https://github.com/go-gitea/gitea
https://github.com/beanvalidation/beanvalidation-api
https://github.com/thanos-io/promql-engine
https://github.com/dotnet/aspnetcore.docs
https://github.com/cfpb/design-system-react
https://github.com/huggingface/transformers
https://github.com/apache/logging-flume
https://github.com/conda-forge/staged-recipes
https://github.com/google/gnostic
https://github.com/dotnet/aspnetcore
https://github.com/aws/smithy-go
https://github.com/jakartaee/rest
https://github.com/istio/istio
https://github.com/azure/azure-sdk-for-js
https://github.com/java-native-access/jna
https://github.com/http-party/node-http-proxy
https://github.com/buildpacks/pack
https://github.com/emissary-ingress/emissary
https://github.com/department-of-veterans-affairs/tech-jam-2013---infusion-
https://github.com/llvm/llvm-project-ci-bridge
https://github.com/streamich/freebsd
https://github.com/redhatinsights/insights-core-1
https://github.com/kubeovn/kube-ovn
https://github.com/apache/arrow-datafusion
https://github.com/apache/datafusion
https://github.com/microsoft/powerapps-tooling
https://github.com/etcd-io/bbolt
https://github.com/microsoft/cloud-hubs
https://github.com/eclipse-ee4j/jaxrs-api
https://github.com/buildpack/lifecycle
https://github.com/nats-io/nats.go
https://github.com/saltstack/salt-jenkins
https://github.com/youtube/vitess
https://github.com/zeebe-io/zeebe
"""

# Split the input into individual lines, remove any empty lines,
# wrap each URL in single quotes, and add a comma at the end.
lines = [line.strip() for line in urls.splitlines() if line.strip()]
transformed = "\n".join([f"'{line}'," for line in lines])

# Write the transformed content to a file.
with open("transformed_urls.txt", "w", encoding="utf-8") as file:
    file.write(transformed)

print("File 'transformed_urls.txt' has been created successfully!")